# Generated by Django 4.1 on 2022-08-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
