# Generated by Django 4.1 on 2022-08-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_cliente_tipo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeCliente',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.TextField()),
                ('tarjetas_de_debito', models.TextField(blank=True, null=True)),
                ('caja_de_ahorro', models.TextField(blank=True, null=True)),
                ('caja_de_ahorro_usd', models.TextField()),
                ('descubierto', models.IntegerField()),
                ('tarjetas_de_credito', models.IntegerField()),
                ('retiro_de_efectivo', models.IntegerField()),
                ('chequeras', models.IntegerField()),
                ('comision_por_transferencia', models.IntegerField()),
                ('max_transferencias', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_de_cliente',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.tiposdecliente'),
        ),
    ]
