# Generated by Django 4.1 on 2022-08-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_tiposdecliente_alter_cliente_tipo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tipo_id',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='tiposdecliente',
            name='max_prestamo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
