# Generated by Django 4.1 on 2022-08-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_rename_tipo_id_cliente_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdecliente',
            name='comision_por_transferencia',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
