# Generated by Django 4.1 on 2022-08-10 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcasDeTarjeta',
            fields=[
                ('marca_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.TextField()),
            ],
            options={
                'db_table': 'marcas_de_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('tarjeta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True)),
                ('cvv', models.IntegerField()),
                ('fecha_otorgamiento', models.TextField()),
                ('fecha_expiracion', models.TextField()),
                ('tipo', models.TextField()),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tarjetas.marcasdetarjeta')),
            ],
            options={
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'tarjetas',
            },
        ),
    ]
