# Generated by Django 4.1 on 2022-08-31 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_alter_cliente_branch_id'),
        ('Tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetas',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='Clientes.cliente'),
        ),
    ]
