# Generated by Django 4.1 on 2022-08-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjetas',
            options={'verbose_name_plural': 'Tarjetas'},
        ),
    ]
