# Generated by Django 4.1 on 2022-08-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='loan_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
