# Generated by Django 4.1 on 2022-08-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0002_alter_prestamo_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
