# Generated by Django 4.1 on 2022-08-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0010_alter_cliente_branch_id'),
        ('Prestamos', '0003_alter_prestamo_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='Clientes.cliente'),
        ),
    ]
